#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boruto.Plugin.Entities
{
	
	
	/// <summary>
	/// Type of relation with business counter party
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum arbo_relationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customer = 500000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Supplier = 500000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Carrier = 500000002,
	}
}
#pragma warning restore CS1591
