#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boruto.Plugin.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bor_demoviews")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public partial class bor_demoviews : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bor_demoviews entity
		/// </summary>
		public partial class Fields
		{
			public const string bor_demoviewsId = "bor_demoviewsid";
			public const string Id = "bor_demoviewsid";
			public const string bor_name = "bor_name";
			public const string bor_number = "bor_number";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bor_demoviews() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bor_demoviews";
		
		public const string EntityLogicalCollectionName = "bor_demoviewses";
		
		public const string EntitySetName = "bor_demoviewses";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bor_demoviewsid")]
		public System.Nullable<System.Guid> bor_demoviewsId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bor_demoviewsid");
			}
			set
			{
				this.OnPropertyChanging("bor_demoviewsId");
				this.SetAttributeValue("bor_demoviewsid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("bor_demoviewsId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bor_demoviewsid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bor_demoviewsId = value;
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bor_name")]
		public string bor_name
		{
			get
			{
				return this.GetAttributeValue<string>("bor_name");
			}
			set
			{
				this.OnPropertyChanging("bor_name");
				this.SetAttributeValue("bor_name", value);
				this.OnPropertyChanged("bor_name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bor_number")]
		public System.Nullable<int> bor_number
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bor_number");
			}
			set
			{
				this.OnPropertyChanging("bor_number");
				this.SetAttributeValue("bor_number", value);
				this.OnPropertyChanged("bor_number");
			}
		}
	}
}
#pragma warning restore CS1591
