/*
 * This file is autogenerated on 2025-07-17 08:17. Manual changes will be overridden on next generate.
 */
namespace Boruto.Plugin.Entities
{
	public partial interface IUnitOfWork
	{
		IRepository<Account> Accounts { get; }
		IRepository<bor_plugindemo> Plugindemos { get; }
		IRepository<bor_demoviews> Demoviewss { get; }
		IRepository<bor_role> Bor_roles { get; }
		IRepository<bor_tab2> Tab2s { get; }
		IRepository<SystemUser> SystemUsers { get; }
		IRepository<Contact> Contacts { get; }
		IRepository<Role> Roles { get; }
	}
}
