#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boruto.Plugin.Entities
{
	
	
	/// <summary>
	/// Har de et budget?
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum budgetstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Intetbindendebudget = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Kbermske = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Kankbe = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Kber = 3,
	}
}
#pragma warning restore CS1591
