#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boruto.Plugin.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum hofor_kontakttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Vandforsyning = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Firma = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Privatperson = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KbenhavnsEnergi = 4,
	}
}
#pragma warning restore CS1591
