#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boruto.Plugin.Entities
{
	
	
	/// <summary>
	/// Om der har været indledende kommunikation med dette kundeemne.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum initialcommunication
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Kontaktet = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ikkekontaktet = 1,
	}
}
#pragma warning restore CS1591
