#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boruto.Plugin.Entities
{
	
	
	/// <summary>
	/// Tilladelse til at udføre en handling i Microsoft CRM. Platformen kontrollerer rettighederne, og brugeren nægtes adgang, hvis vedkommende ikke har de nødvendige rettigheder.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("privilege")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class Privilege : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the privilege entity
		/// </summary>
		public partial class Fields
		{
			public const string AccessRight = "accessright";
			public const string CanBeBasic = "canbebasic";
			public const string CanBeBasicName = "canbebasicname";
			public const string CanBeDeep = "canbedeep";
			public const string CanBeDeepName = "canbedeepname";
			public const string CanBeEntityReference = "canbeentityreference";
			public const string CanBeEntityReferenceName = "canbeentityreferencename";
			public const string CanBeGlobal = "canbeglobal";
			public const string CanBeGlobalName = "canbeglobalname";
			public const string CanBeLocal = "canbelocal";
			public const string CanBeLocalName = "canbelocalname";
			public const string CanBeParentEntityReference = "canbeparententityreference";
			public const string CanBeParentEntityReferenceName = "canbeparententityreferencename";
			public const string CanBeRecordFilter = "canberecordfilter";
			public const string canberecordfilterName = "canberecordfiltername";
			public const string ComponentState = "componentstate";
			public const string IntroducedVersion = "introducedversion";
			public const string IsCustomizable = "iscustomizable";
			public const string IsManaged = "ismanaged";
			public const string IsManagedName = "ismanagedname";
			public const string Name = "name";
			public const string OverwriteTime = "overwritetime";
			public const string PrivilegeId = "privilegeid";
			public const string Id = "privilegeid";
			public const string PrivilegeRowId = "privilegerowid";
			public const string SolutionId = "solutionid";
			public const string VersionNumber = "versionnumber";
			public const string roleprivileges_association = "roleprivileges_association";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Privilege() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "privilege";
		
		public const string EntityLogicalCollectionName = "privileges";
		
		public const string EntitySetName = "privileges";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// De rettigheder, som en bruger har til en forekomst af et objekt.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accessright")]
		public System.Nullable<int> AccessRight
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("accessright");
			}
			set
			{
				this.OnPropertyChanging("AccessRight");
				this.SetAttributeValue("accessright", value);
				this.OnPropertyChanged("AccessRight");
			}
		}
		
		/// <summary>
		/// Angiver, om rettigheden gælder for brugeren, brugerens gruppe eller for de objekter, der deles af brugeren.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbebasic")]
		public System.Nullable<bool> CanBeBasic
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("canbebasic");
			}
			set
			{
				this.OnPropertyChanging("CanBeBasic");
				this.SetAttributeValue("canbebasic", value);
				this.OnPropertyChanged("CanBeBasic");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbebasicname")]
		public string CanBeBasicName
		{
			get
			{
				if (this.FormattedValues.Contains("canbebasic"))
				{
					return this.FormattedValues["canbebasic"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Angiver, om rettigheden gælder for underordnede afdelinger til den afdeling, der er tilknyttet brugeren.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbedeep")]
		public System.Nullable<bool> CanBeDeep
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("canbedeep");
			}
			set
			{
				this.OnPropertyChanging("CanBeDeep");
				this.SetAttributeValue("canbedeep", value);
				this.OnPropertyChanged("CanBeDeep");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbedeepname")]
		public string CanBeDeepName
		{
			get
			{
				if (this.FormattedValues.Contains("canbedeep"))
				{
					return this.FormattedValues["canbedeep"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Oplysninger, der angiver, om rettigheden gælder for en ekstern parts lokale reference.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbeentityreference")]
		public System.Nullable<bool> CanBeEntityReference
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("canbeentityreference");
			}
			set
			{
				this.OnPropertyChanging("CanBeEntityReference");
				this.SetAttributeValue("canbeentityreference", value);
				this.OnPropertyChanged("CanBeEntityReference");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbeentityreferencename")]
		public string CanBeEntityReferenceName
		{
			get
			{
				if (this.FormattedValues.Contains("canbeentityreference"))
				{
					return this.FormattedValues["canbeentityreference"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Angiver, om rettigheden gælder for hele organisationen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbeglobal")]
		public System.Nullable<bool> CanBeGlobal
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("canbeglobal");
			}
			set
			{
				this.OnPropertyChanging("CanBeGlobal");
				this.SetAttributeValue("canbeglobal", value);
				this.OnPropertyChanged("CanBeGlobal");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbeglobalname")]
		public string CanBeGlobalName
		{
			get
			{
				if (this.FormattedValues.Contains("canbeglobal"))
				{
					return this.FormattedValues["canbeglobal"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Angiver, om rettigheden gælder for brugerens afdeling.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbelocal")]
		public System.Nullable<bool> CanBeLocal
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("canbelocal");
			}
			set
			{
				this.OnPropertyChanging("CanBeLocal");
				this.SetAttributeValue("canbelocal", value);
				this.OnPropertyChanged("CanBeLocal");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbelocalname")]
		public string CanBeLocalName
		{
			get
			{
				if (this.FormattedValues.Contains("canbelocal"))
				{
					return this.FormattedValues["canbelocal"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Oplysninger, der angiver, om rettigheden gælder for den eksterne parts overordnede reference.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbeparententityreference")]
		public System.Nullable<bool> CanBeParentEntityReference
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("canbeparententityreference");
			}
			set
			{
				this.OnPropertyChanging("CanBeParentEntityReference");
				this.SetAttributeValue("canbeparententityreference", value);
				this.OnPropertyChanged("CanBeParentEntityReference");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canbeparententityreferencename")]
		public string CanBeParentEntityReferenceName
		{
			get
			{
				if (this.FormattedValues.Contains("canbeparententityreference"))
				{
					return this.FormattedValues["canbeparententityreference"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Oplysninger, der angiver, om rettigheden gælder for postfiltrene.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canberecordfilter")]
		public System.Nullable<bool> CanBeRecordFilter
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("canberecordfilter");
			}
			set
			{
				this.OnPropertyChanging("CanBeRecordFilter");
				this.SetAttributeValue("canberecordfilter", value);
				this.OnPropertyChanged("CanBeRecordFilter");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canberecordfiltername")]
		public string canberecordfilterName
		{
			get
			{
				if (this.FormattedValues.Contains("canberecordfilter"))
				{
					return this.FormattedValues["canberecordfilter"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Kun til intern brug.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Version, som komponenten introduceres i.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("introducedversion")]
		public string IntroducedVersion
		{
			get
			{
				return this.GetAttributeValue<string>("introducedversion");
			}
			set
			{
				this.OnPropertyChanging("IntroducedVersion");
				this.SetAttributeValue("introducedversion", value);
				this.OnPropertyChanged("IntroducedVersion");
			}
		}
		
		/// <summary>
		/// Oplysninger, der angiver, om denne komponent kan tilpasses.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.OnPropertyChanging("IsCustomizable");
				this.SetAttributeValue("iscustomizable", value);
				this.OnPropertyChanged("IsCustomizable");
			}
		}
		
		/// <summary>
		/// Oplysning om, hvorvidt komponenten er administreret.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanagedname")]
		public string IsManagedName
		{
			get
			{
				if (this.FormattedValues.Contains("ismanaged"))
				{
					return this.FormattedValues["ismanaged"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Navnet på rettigheden.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Kun til intern brug.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Entydigt id for rettigheden.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("privilegeid")]
		public System.Nullable<System.Guid> PrivilegeId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("privilegeid");
			}
			set
			{
				this.OnPropertyChanging("PrivilegeId");
				this.SetAttributeValue("privilegeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("PrivilegeId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("privilegeid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.PrivilegeId = value;
			}
		}
		
		/// <summary>
		/// Entydigt id for den rettighed, der bruges til synkronisering af tilpasninger med Microsoft Dynamics CRM-klienten til Outlook
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("privilegerowid")]
		public System.Nullable<System.Guid> PrivilegeRowId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("privilegerowid");
			}
			set
			{
				this.OnPropertyChanging("PrivilegeRowId");
				this.SetAttributeValue("privilegerowid", value);
				this.OnPropertyChanged("PrivilegeRowId");
			}
		}
		
		/// <summary>
		/// Entydigt id for den tilknyttede løsning.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N roleprivileges_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("roleprivileges_association")]
		public System.Collections.Generic.IEnumerable<Boruto.Plugin.Entities.Role> roleprivileges_association
		{
			get
			{
				return this.GetRelatedEntities<Boruto.Plugin.Entities.Role>("roleprivileges_association", null);
			}
			set
			{
				this.OnPropertyChanging("roleprivileges_association");
				this.SetRelatedEntities<Boruto.Plugin.Entities.Role>("roleprivileges_association", null, value);
				this.OnPropertyChanged("roleprivileges_association");
			}
		}
	}
}
#pragma warning restore CS1591
