#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boruto.Plugin.Entities
{
	
	
	/// <summary>
	/// Fragtbetingelser for tilbuddet.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum quote_freighttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FOB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Udenberegning = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum msdyn_quote_msdyn_ordertype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Elementbaseret = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Servicevedligeholdelsesbaseret = 690970002,
	}
	
	/// <summary>
	/// Betalingsbetingelser for tilbuddet.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum quote_paymenttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Netto30dage = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Netto8dage = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Netto14dage = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nettokontant = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lbendemned14dage = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lbendemned8dage = 12,
	}
	
	/// <summary>
	/// Forsendelsesmåde for tilbuddet.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum quote_shippingmethodcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Luftfragt = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DHL = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FedEx = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UPS = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Almpost = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Andet = 8,
	}
	
	/// <summary>
	/// Fragtbetingelser for forsendelsesadressen.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum quote_shipto_freighttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Standardvrdi = 1,
	}
	
	/// <summary>
	/// Status for tilbuddet.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum quote_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Won = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 3,
	}
	
	/// <summary>
	/// Årsag til statussen for tilbuddet.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum quote_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Igang = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ben = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Vundet = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tabt = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Annulleret = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Senestopdateret = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Igang1 = 1,
	}
	
	/// <summary>
	/// Formelt tilbud på produkter og/eller servicer, der tilbydes til bestemte priser og betalingsbetingelser, som sendes til en potentiel kunde.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("quote")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class Quote : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the quote entity
		/// </summary>
		public partial class Fields
		{
			public const string AccountId = "accountid";
			public const string AccountIdName = "accountidname";
			public const string AccountIdYomiName = "accountidyominame";
			public const string BillTo_AddressId = "billto_addressid";
			public const string BillTo_City = "billto_city";
			public const string BillTo_Composite = "billto_composite";
			public const string BillTo_ContactName = "billto_contactname";
			public const string BillTo_Country = "billto_country";
			public const string BillTo_Fax = "billto_fax";
			public const string BillTo_Line1 = "billto_line1";
			public const string BillTo_Line2 = "billto_line2";
			public const string BillTo_Line3 = "billto_line3";
			public const string BillTo_Name = "billto_name";
			public const string BillTo_PostalCode = "billto_postalcode";
			public const string BillTo_StateOrProvince = "billto_stateorprovince";
			public const string BillTo_Telephone = "billto_telephone";
			public const string CampaignId = "campaignid";
			public const string CampaignIdName = "campaignidname";
			public const string ClosedOn = "closedon";
			public const string ContactId = "contactid";
			public const string ContactIdName = "contactidname";
			public const string ContactIdYomiName = "contactidyominame";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string CustomerId = "customerid";
			public const string CustomerIdName = "customeridname";
			public const string CustomerIdYomiName = "customeridyominame";
			public const string Description = "description";
			public const string DiscountAmount = "discountamount";
			public const string DiscountAmount_Base = "discountamount_base";
			public const string DiscountPercentage = "discountpercentage";
			public const string EffectiveFrom = "effectivefrom";
			public const string EffectiveTo = "effectiveto";
			public const string EmailAddress = "emailaddress";
			public const string ExchangeRate = "exchangerate";
			public const string ExpiresOn = "expireson";
			public const string FreightAmount = "freightamount";
			public const string FreightAmount_Base = "freightamount_base";
			public const string FreightTermsCode = "freighttermscode";
			public const string FreightTermsCodeName = "freighttermscodename";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string LastOnHoldTime = "lastonholdtime";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string msdyn_Account = "msdyn_account";
			public const string msdyn_AccountName = "msdyn_accountname";
			public const string msdyn_AccountYomiName = "msdyn_accountyominame";
			public const string msdyn_EstimatedCost = "msdyn_estimatedcost";
			public const string msdyn_estimatedcost_Base = "msdyn_estimatedcost_base";
			public const string msdyn_EstimatedQuoteMargin = "msdyn_estimatedquotemargin";
			public const string msdyn_InvoiceSetupTotals = "msdyn_invoicesetuptotals";
			public const string msdyn_invoicesetuptotals_Base = "msdyn_invoicesetuptotals_base";
			public const string msdyn_OrderType = "msdyn_ordertype";
			public const string msdyn_ordertypeName = "msdyn_ordertypename";
			public const string msdyn_QuoteLineEndDate = "msdyn_quotelineenddate";
			public const string msdyn_QuoteLineStartDate = "msdyn_quotelinestartdate";
			public const string msdyn_TotalAmount = "msdyn_totalamount";
			public const string msdyn_totalamount_Base = "msdyn_totalamount_base";
			public const string Name = "name";
			public const string OnHoldTime = "onholdtime";
			public const string OpportunityId = "opportunityid";
			public const string OpportunityIdName = "opportunityidname";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string PaymentTermsCode = "paymenttermscode";
			public const string PaymentTermsCodeName = "paymenttermscodename";
			public const string PriceLevelId = "pricelevelid";
			public const string PriceLevelIdName = "pricelevelidname";
			public const string PricingErrorCode = "pricingerrorcode";
			public const string PricingErrorCodeName = "pricingerrorcodename";
			public const string ProcessId = "processid";
			public const string QuoteCreationMethod = "quotecreationmethod";
			public const string quotecreationmethodName = "quotecreationmethodname";
			public const string QuoteId = "quoteid";
			public const string Id = "quoteid";
			public const string QuoteNumber = "quotenumber";
			public const string RequestDeliveryBy = "requestdeliveryby";
			public const string RevisionNumber = "revisionnumber";
			public const string ShippingMethodCode = "shippingmethodcode";
			public const string ShippingMethodCodeName = "shippingmethodcodename";
			public const string ShipTo_AddressId = "shipto_addressid";
			public const string ShipTo_City = "shipto_city";
			public const string ShipTo_Composite = "shipto_composite";
			public const string ShipTo_ContactName = "shipto_contactname";
			public const string ShipTo_Country = "shipto_country";
			public const string ShipTo_Fax = "shipto_fax";
			public const string ShipTo_FreightTermsCode = "shipto_freighttermscode";
			public const string ShipTo_FreightTermsCodeName = "shipto_freighttermscodename";
			public const string ShipTo_Line1 = "shipto_line1";
			public const string ShipTo_Line2 = "shipto_line2";
			public const string ShipTo_Line3 = "shipto_line3";
			public const string ShipTo_Name = "shipto_name";
			public const string ShipTo_PostalCode = "shipto_postalcode";
			public const string ShipTo_StateOrProvince = "shipto_stateorprovince";
			public const string ShipTo_Telephone = "shipto_telephone";
			public const string SkipPriceCalculation = "skippricecalculation";
			public const string skippricecalculationName = "skippricecalculationname";
			public const string SLAId = "slaid";
			public const string SLAInvokedId = "slainvokedid";
			public const string SLAInvokedIdName = "slainvokedidname";
			public const string SLAName = "slaname";
			public const string StageId = "stageid";
			public const string StateCode = "statecode";
			public const string StateCodeName = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TotalAmount = "totalamount";
			public const string TotalAmount_Base = "totalamount_base";
			public const string TotalAmountLessFreight = "totalamountlessfreight";
			public const string TotalAmountLessFreight_Base = "totalamountlessfreight_base";
			public const string TotalDiscountAmount = "totaldiscountamount";
			public const string TotalDiscountAmount_Base = "totaldiscountamount_base";
			public const string TotalLineItemAmount = "totallineitemamount";
			public const string TotalLineItemAmount_Base = "totallineitemamount_base";
			public const string TotalLineItemDiscountAmount = "totallineitemdiscountamount";
			public const string TotalLineItemDiscountAmount_Base = "totallineitemdiscountamount_base";
			public const string TotalTax = "totaltax";
			public const string TotalTax_Base = "totaltax_base";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TransactionCurrencyIdName = "transactioncurrencyidname";
			public const string TraversedPath = "traversedpath";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string WillCall = "willcall";
			public const string WillCallName = "willcallname";
			public const string contactquotes_association = "contactquotes_association";
			public const string business_unit_quotes = "business_unit_quotes";
			public const string lk_quote_createdonbehalfby = "lk_quote_createdonbehalfby";
			public const string lk_quote_modifiedonbehalfby = "lk_quote_modifiedonbehalfby";
			public const string lk_quotebase_createdby = "lk_quotebase_createdby";
			public const string lk_quotebase_modifiedby = "lk_quotebase_modifiedby";
			public const string msdyn_account_quote_Account = "msdyn_account_quote_Account";
			public const string opportunity_quotes = "opportunity_quotes";
			public const string quote_customer_accounts = "quote_customer_accounts";
			public const string quote_customer_contacts = "quote_customer_contacts";
			public const string system_user_quotes = "system_user_quotes";
			public const string team_quotes = "team_quotes";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Quote() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "quote";
		
		public const string EntityLogicalCollectionName = "quotes";
		
		public const string EntitySetName = "quotes";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Entydigt id for det firma, som tilbuddet er tilknyttet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountid")]
		public Microsoft.Xrm.Sdk.EntityReference AccountId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("accountid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountidname")]
		public string AccountIdName
		{
			get
			{
				if (this.FormattedValues.Contains("accountid"))
				{
					return this.FormattedValues["accountid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountidyominame")]
		public string AccountIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("accountid"))
				{
					return this.FormattedValues["accountid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Entydigt id for faktureringsadressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_addressid")]
		public System.Nullable<System.Guid> BillTo_AddressId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("billto_addressid");
			}
			set
			{
				this.OnPropertyChanging("BillTo_AddressId");
				this.SetAttributeValue("billto_addressid", value);
				this.OnPropertyChanged("BillTo_AddressId");
			}
		}
		
		/// <summary>
		/// Angiv byen for kundens faktureringsadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_city")]
		public string BillTo_City
		{
			get
			{
				return this.GetAttributeValue<string>("billto_city");
			}
			set
			{
				this.OnPropertyChanging("BillTo_City");
				this.SetAttributeValue("billto_city", value);
				this.OnPropertyChanged("BillTo_City");
			}
		}
		
		/// <summary>
		/// Viser den fulde faktureringsadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_composite")]
		public string BillTo_Composite
		{
			get
			{
				return this.GetAttributeValue<string>("billto_composite");
			}
		}
		
		/// <summary>
		/// Angiv navnet på den primære kontakt på kundens faktureringsadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_contactname")]
		public string BillTo_ContactName
		{
			get
			{
				return this.GetAttributeValue<string>("billto_contactname");
			}
			set
			{
				this.OnPropertyChanging("BillTo_ContactName");
				this.SetAttributeValue("billto_contactname", value);
				this.OnPropertyChanged("BillTo_ContactName");
			}
		}
		
		/// <summary>
		/// Angiv landet eller området for kundens faktureringsadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_country")]
		public string BillTo_Country
		{
			get
			{
				return this.GetAttributeValue<string>("billto_country");
			}
			set
			{
				this.OnPropertyChanging("BillTo_Country");
				this.SetAttributeValue("billto_country", value);
				this.OnPropertyChanged("BillTo_Country");
			}
		}
		
		/// <summary>
		/// Angiv faxnummeret for kundens faktureringsadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_fax")]
		public string BillTo_Fax
		{
			get
			{
				return this.GetAttributeValue<string>("billto_fax");
			}
			set
			{
				this.OnPropertyChanging("BillTo_Fax");
				this.SetAttributeValue("billto_fax", value);
				this.OnPropertyChanged("BillTo_Fax");
			}
		}
		
		/// <summary>
		/// Angiv den første linje i kundens faktureringsadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line1")]
		public string BillTo_Line1
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line1");
			}
			set
			{
				this.OnPropertyChanging("BillTo_Line1");
				this.SetAttributeValue("billto_line1", value);
				this.OnPropertyChanged("BillTo_Line1");
			}
		}
		
		/// <summary>
		/// Angiv den anden linje i kundens faktureringsadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line2")]
		public string BillTo_Line2
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line2");
			}
			set
			{
				this.OnPropertyChanging("BillTo_Line2");
				this.SetAttributeValue("billto_line2", value);
				this.OnPropertyChanged("BillTo_Line2");
			}
		}
		
		/// <summary>
		/// Angiv den tredje linje i faktureringsadressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line3")]
		public string BillTo_Line3
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line3");
			}
			set
			{
				this.OnPropertyChanging("BillTo_Line3");
				this.SetAttributeValue("billto_line3", value);
				this.OnPropertyChanged("BillTo_Line3");
			}
		}
		
		/// <summary>
		/// Angiv et navn til kundens faktureringsadresse, f.eks. "Hovedsæde" eller "Afdelingskontor", for at identificere adressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_name")]
		public string BillTo_Name
		{
			get
			{
				return this.GetAttributeValue<string>("billto_name");
			}
			set
			{
				this.OnPropertyChanging("BillTo_Name");
				this.SetAttributeValue("billto_name", value);
				this.OnPropertyChanged("BillTo_Name");
			}
		}
		
		/// <summary>
		/// Angiv postnummeret i faktureringsadressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_postalcode")]
		public string BillTo_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("billto_postalcode");
			}
			set
			{
				this.OnPropertyChanging("BillTo_PostalCode");
				this.SetAttributeValue("billto_postalcode", value);
				this.OnPropertyChanged("BillTo_PostalCode");
			}
		}
		
		/// <summary>
		/// Angiv staten eller området for faktureringsadressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_stateorprovince")]
		public string BillTo_StateOrProvince
		{
			get
			{
				return this.GetAttributeValue<string>("billto_stateorprovince");
			}
			set
			{
				this.OnPropertyChanging("BillTo_StateOrProvince");
				this.SetAttributeValue("billto_stateorprovince", value);
				this.OnPropertyChanged("BillTo_StateOrProvince");
			}
		}
		
		/// <summary>
		/// Angiv telefonnummeret for kundens faktureringsadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_telephone")]
		public string BillTo_Telephone
		{
			get
			{
				return this.GetAttributeValue<string>("billto_telephone");
			}
			set
			{
				this.OnPropertyChanging("BillTo_Telephone");
				this.SetAttributeValue("billto_telephone", value);
				this.OnPropertyChanged("BillTo_Telephone");
			}
		}
		
		/// <summary>
		/// Viser den kampagne, som ordren er oprettet ud fra.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("campaignid")]
		public Microsoft.Xrm.Sdk.EntityReference CampaignId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("campaignid");
			}
			set
			{
				this.OnPropertyChanging("CampaignId");
				this.SetAttributeValue("campaignid", value);
				this.OnPropertyChanged("CampaignId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("campaignidname")]
		public string CampaignIdName
		{
			get
			{
				if (this.FormattedValues.Contains("campaignid"))
				{
					return this.FormattedValues["campaignid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Angiv den dato, da tilbuddet blev lukket, for at angive udløbs-, revisions- eller annulleringsdatoen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("closedon")]
		public System.Nullable<System.DateTime> ClosedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("closedon");
			}
			set
			{
				this.OnPropertyChanging("ClosedOn");
				this.SetAttributeValue("closedon", value);
				this.OnPropertyChanged("ClosedOn");
			}
		}
		
		/// <summary>
		/// Entydigt id for den kontaktperson, der er tilknyttet tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactid")]
		public Microsoft.Xrm.Sdk.EntityReference ContactId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contactid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactidname")]
		public string ContactIdName
		{
			get
			{
				if (this.FormattedValues.Contains("contactid"))
				{
					return this.FormattedValues["contactid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactidyominame")]
		public string ContactIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("contactid"))
				{
					return this.FormattedValues["contactid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Viser, hvem der oprettede posten.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Viser, hvem der oprettede posten på vegne af en anden bruger.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Vælg kundefirmaet eller -kontakten for at angive et hurtigt link til flere kundeoplysninger som f.eks. firmaoplysninger, aktiviteter og salgsmuligheder.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		public Microsoft.Xrm.Sdk.EntityReference CustomerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("customerid");
			}
			set
			{
				this.OnPropertyChanging("CustomerId");
				this.SetAttributeValue("customerid", value);
				this.OnPropertyChanged("CustomerId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customeridname")]
		public string CustomerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("customerid"))
				{
					return this.FormattedValues["customerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customeridyominame")]
		public string CustomerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("customerid"))
				{
					return this.FormattedValues["customerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Angiv flere oplysninger for at beskrive tilbuddet, f.eks. de tilbudte produkter eller servicer eller oplysninger om kundens produktpræferencer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// Angiv rabatbeløbet for tilbuddet, hvis kunden er berettiget til særrabat.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount")]
		public Microsoft.Xrm.Sdk.Money DiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount");
			}
			set
			{
				this.OnPropertyChanging("DiscountAmount");
				this.SetAttributeValue("discountamount", value);
				this.OnPropertyChanged("DiscountAmount");
			}
		}
		
		/// <summary>
		/// Value of the Rabatbeløb i tilbud in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount_base")]
		public Microsoft.Xrm.Sdk.Money DiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount_base");
			}
		}
		
		/// <summary>
		/// Angiv den rabatprocent, der skal anvendes i feltet Detaljebeløb, for at inkludere yderligere besparelser for kunden i tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountpercentage")]
		public System.Nullable<decimal> DiscountPercentage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("discountpercentage");
			}
			set
			{
				this.OnPropertyChanging("DiscountPercentage");
				this.SetAttributeValue("discountpercentage", value);
				this.OnPropertyChanged("DiscountPercentage");
			}
		}
		
		/// <summary>
		/// Angiv den dato, hvor tilbuddets prissætning gælder fra eller første gang blev meddelt til kunden.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("effectivefrom")]
		public System.Nullable<System.DateTime> EffectiveFrom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("effectivefrom");
			}
			set
			{
				this.OnPropertyChanging("EffectiveFrom");
				this.SetAttributeValue("effectivefrom", value);
				this.OnPropertyChanged("EffectiveFrom");
			}
		}
		
		/// <summary>
		/// Angiv udløbsdatoen eller den sidste dag, tilbuddets prissætning gælder for kunden.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("effectiveto")]
		public System.Nullable<System.DateTime> EffectiveTo
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("effectiveto");
			}
			set
			{
				this.OnPropertyChanging("EffectiveTo");
				this.SetAttributeValue("effectiveto", value);
				this.OnPropertyChanged("EffectiveTo");
			}
		}
		
		/// <summary>
		/// The primary email address for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
		public string EmailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("emailaddress");
			}
			set
			{
				this.OnPropertyChanging("EmailAddress");
				this.SetAttributeValue("emailaddress", value);
				this.OnPropertyChanged("EmailAddress");
			}
		}
		
		/// <summary>
		/// Viser omregningskursen for postens valuta. Valutakursen bruges til at konvertere alle pengefelter i posten fra den lokale valuta til systemets standardvaluta.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Angiv den dato, hvor en beslutning eller ordre forfalder for kunden, for at angive tilbuddets udløbsdato.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("expireson")]
		public System.Nullable<System.DateTime> ExpiresOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("expireson");
			}
			set
			{
				this.OnPropertyChanging("ExpiresOn");
				this.SetAttributeValue("expireson", value);
				this.OnPropertyChanged("ExpiresOn");
			}
		}
		
		/// <summary>
		/// Angiv fragt- eller forsendelsesomkostningerne for de produkter, der er inkluderet i tilbuddet, til brug ved beregning af feltet Samlet beløb.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount")]
		public Microsoft.Xrm.Sdk.Money FreightAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount");
			}
			set
			{
				this.OnPropertyChanging("FreightAmount");
				this.SetAttributeValue("freightamount", value);
				this.OnPropertyChanged("FreightAmount");
			}
		}
		
		/// <summary>
		/// Value of the Fragtbeløb in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount_base")]
		public Microsoft.Xrm.Sdk.Money FreightAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount_base");
			}
		}
		
		/// <summary>
		/// Vælg fragtbetingelserne for at sikre, at forsendelsesgebyrer behandles korrekt.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freighttermscode")]
		public virtual quote_freighttermscode? FreightTermsCode
		{
			get
			{
				return ((quote_freighttermscode?)(EntityOptionSetEnum.GetEnum(this, "freighttermscode")));
			}
			set
			{
				this.OnPropertyChanging("FreightTermsCode");
				this.SetAttributeValue("freighttermscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("FreightTermsCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freighttermscodename")]
		public string FreightTermsCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("freighttermscode"))
				{
					return this.FormattedValues["freighttermscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Indeholder datotidsstemplet for den seneste tid for I venteposition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastonholdtime")]
		public System.Nullable<System.DateTime> LastOnHoldTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
			}
			set
			{
				this.OnPropertyChanging("LastOnHoldTime");
				this.SetAttributeValue("lastonholdtime", value);
				this.OnPropertyChanged("LastOnHoldTime");
			}
		}
		
		/// <summary>
		/// Viser, hvem der sidst opdaterede posten.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Viser, hvem der sidst opdaterede posten på vegne af en anden bruger.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Kundekonto, der er tilknyttet dette tilbud
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_account")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Account
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_account");
			}
			set
			{
				this.OnPropertyChanging("msdyn_Account");
				this.SetAttributeValue("msdyn_account", value);
				this.OnPropertyChanged("msdyn_Account");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_accountname")]
		public string msdyn_AccountName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_account"))
				{
					return this.FormattedValues["msdyn_account"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_accountyominame")]
		public string msdyn_AccountYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_account"))
				{
					return this.FormattedValues["msdyn_account"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Den anslåede omkostning for dette tilbud
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_estimatedcost")]
		public Microsoft.Xrm.Sdk.Money msdyn_EstimatedCost
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_estimatedcost");
			}
			set
			{
				this.OnPropertyChanging("msdyn_EstimatedCost");
				this.SetAttributeValue("msdyn_estimatedcost", value);
				this.OnPropertyChanged("msdyn_EstimatedCost");
			}
		}
		
		/// <summary>
		/// Værdien af de anslåede omkostninger i grundvalutaen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_estimatedcost_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_estimatedcost_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_estimatedcost_base");
			}
		}
		
		/// <summary>
		/// Anslået avance for dette tilbud
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_estimatedquotemargin")]
		public System.Nullable<decimal> msdyn_EstimatedQuoteMargin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_estimatedquotemargin");
			}
		}
		
		/// <summary>
		/// Totalerne for alle tildelte fakturakonfigurationer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_invoicesetuptotals")]
		public Microsoft.Xrm.Sdk.Money msdyn_InvoiceSetupTotals
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_invoicesetuptotals");
			}
			set
			{
				this.OnPropertyChanging("msdyn_InvoiceSetupTotals");
				this.SetAttributeValue("msdyn_invoicesetuptotals", value);
				this.OnPropertyChanged("msdyn_InvoiceSetupTotals");
			}
		}
		
		/// <summary>
		/// Værdien af totaler i fakturakonfiguration i grundvalutaen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_invoicesetuptotals_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_invoicesetuptotals_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_invoicesetuptotals_base");
			}
		}
		
		/// <summary>
		/// Kun til intern brug.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_ordertype")]
		public virtual msdyn_quote_msdyn_ordertype? msdyn_OrderType
		{
			get
			{
				return ((msdyn_quote_msdyn_ordertype?)(EntityOptionSetEnum.GetEnum(this, "msdyn_ordertype")));
			}
			set
			{
				this.OnPropertyChanging("msdyn_OrderType");
				this.SetAttributeValue("msdyn_ordertype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdyn_OrderType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_ordertypename")]
		public string msdyn_ordertypeName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_ordertype"))
				{
					return this.FormattedValues["msdyn_ordertype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Den seneste slutdato for alle tilknyttede tilbudslinjer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_quotelineenddate")]
		public System.Nullable<System.DateTime> msdyn_QuoteLineEndDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_quotelineenddate");
			}
			set
			{
				this.OnPropertyChanging("msdyn_QuoteLineEndDate");
				this.SetAttributeValue("msdyn_quotelineenddate", value);
				this.OnPropertyChanged("msdyn_QuoteLineEndDate");
			}
		}
		
		/// <summary>
		/// Den tidligste startdato for alle tilbudslinjer, der er knyttet til dette tilbud
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_quotelinestartdate")]
		public System.Nullable<System.DateTime> msdyn_QuoteLineStartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_quotelinestartdate");
			}
			set
			{
				this.OnPropertyChanging("msdyn_QuoteLineStartDate");
				this.SetAttributeValue("msdyn_quotelinestartdate", value);
				this.OnPropertyChanged("msdyn_QuoteLineStartDate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_totalamount")]
		public Microsoft.Xrm.Sdk.Money msdyn_TotalAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_totalamount");
			}
		}
		
		/// <summary>
		/// Værdien af TotalAmount i grundvalutaen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_totalamount_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_totalamount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_totalamount_base");
			}
		}
		
		/// <summary>
		/// Angiv et beskrivende navn til tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Viser den varighed i minutter, hvor tilbuddet var i venteposition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("onholdtime")]
		public System.Nullable<int> OnHoldTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("onholdtime");
			}
		}
		
		/// <summary>
		/// Vælg den salgsmulighed, som tilbuddet er relateret til, til brug for rapportering og analyser.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opportunityid")]
		public Microsoft.Xrm.Sdk.EntityReference OpportunityId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opportunityid");
			}
			set
			{
				this.OnPropertyChanging("OpportunityId");
				this.SetAttributeValue("opportunityid", value);
				this.OnPropertyChanged("OpportunityId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opportunityidname")]
		public string OpportunityIdName
		{
			get
			{
				if (this.FormattedValues.Contains("opportunityid"))
				{
					return this.FormattedValues["opportunityid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Vælg betalingsbetingelserne for at angive, hvornår kunden skal betale det samlede beløb.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("paymenttermscode")]
		public virtual quote_paymenttermscode? PaymentTermsCode
		{
			get
			{
				return ((quote_paymenttermscode?)(EntityOptionSetEnum.GetEnum(this, "paymenttermscode")));
			}
			set
			{
				this.OnPropertyChanging("PaymentTermsCode");
				this.SetAttributeValue("paymenttermscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("PaymentTermsCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("paymenttermscodename")]
		public string PaymentTermsCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("paymenttermscode"))
				{
					return this.FormattedValues["paymenttermscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Vælg den prisliste, der er tilknyttet denne post, for at sikre, at de produkter, der er knyttet til kampagnen, tilbydes til de korrekte priser.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricelevelid")]
		public Microsoft.Xrm.Sdk.EntityReference PriceLevelId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pricelevelid");
			}
			set
			{
				this.OnPropertyChanging("PriceLevelId");
				this.SetAttributeValue("pricelevelid", value);
				this.OnPropertyChanged("PriceLevelId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricelevelidname")]
		public string PriceLevelIdName
		{
			get
			{
				if (this.FormattedValues.Contains("pricelevelid"))
				{
					return this.FormattedValues["pricelevelid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Prissætningsfejl for tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingerrorcode")]
		public virtual qooi_pricingerrorcode? PricingErrorCode
		{
			get
			{
				return ((qooi_pricingerrorcode?)(EntityOptionSetEnum.GetEnum(this, "pricingerrorcode")));
			}
			set
			{
				this.OnPropertyChanging("PricingErrorCode");
				this.SetAttributeValue("pricingerrorcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("PricingErrorCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingerrorcodename")]
		public string PricingErrorCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("pricingerrorcode"))
				{
					return this.FormattedValues["pricingerrorcode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.OnPropertyChanging("ProcessId");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("ProcessId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quotecreationmethod")]
		public virtual quotecreationmethod? QuoteCreationMethod
		{
			get
			{
				return ((quotecreationmethod?)(EntityOptionSetEnum.GetEnum(this, "quotecreationmethod")));
			}
			set
			{
				this.OnPropertyChanging("QuoteCreationMethod");
				this.SetAttributeValue("quotecreationmethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("QuoteCreationMethod");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quotecreationmethodname")]
		public string quotecreationmethodName
		{
			get
			{
				if (this.FormattedValues.Contains("quotecreationmethod"))
				{
					return this.FormattedValues["quotecreationmethod"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Entydigt id for tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quoteid")]
		public System.Nullable<System.Guid> QuoteId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("quoteid");
			}
			set
			{
				this.OnPropertyChanging("QuoteId");
				this.SetAttributeValue("quoteid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("QuoteId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quoteid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.QuoteId = value;
			}
		}
		
		/// <summary>
		/// Viser tilbudsnummeret som kundereference og til søgefunktioner. Nummeret kan ikke redigeres.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quotenumber")]
		public string QuoteNumber
		{
			get
			{
				return this.GetAttributeValue<string>("quotenumber");
			}
			set
			{
				this.OnPropertyChanging("QuoteNumber");
				this.SetAttributeValue("quotenumber", value);
				this.OnPropertyChanged("QuoteNumber");
			}
		}
		
		/// <summary>
		/// Angiv den leveringsdato, som kunden har anmodet om, for alle produkter i tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requestdeliveryby")]
		public System.Nullable<System.DateTime> RequestDeliveryBy
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("requestdeliveryby");
			}
			set
			{
				this.OnPropertyChanging("RequestDeliveryBy");
				this.SetAttributeValue("requestdeliveryby", value);
				this.OnPropertyChanged("RequestDeliveryBy");
			}
		}
		
		/// <summary>
		/// Viser versionsnummeret på tilbuddet til brug for sporing af revisionshistorikken.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("revisionnumber")]
		public System.Nullable<int> RevisionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("revisionnumber");
			}
		}
		
		/// <summary>
		/// Vælg en forsendelsesmetode til leverancer, der sendes til denne adresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shippingmethodcode")]
		public virtual quote_shippingmethodcode? ShippingMethodCode
		{
			get
			{
				return ((quote_shippingmethodcode?)(EntityOptionSetEnum.GetEnum(this, "shippingmethodcode")));
			}
			set
			{
				this.OnPropertyChanging("ShippingMethodCode");
				this.SetAttributeValue("shippingmethodcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ShippingMethodCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shippingmethodcodename")]
		public string ShippingMethodCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("shippingmethodcode"))
				{
					return this.FormattedValues["shippingmethodcode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Entydigt id for forsendelsesadressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_addressid")]
		public System.Nullable<System.Guid> ShipTo_AddressId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("shipto_addressid");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_AddressId");
				this.SetAttributeValue("shipto_addressid", value);
				this.OnPropertyChanged("ShipTo_AddressId");
			}
		}
		
		/// <summary>
		/// Angiv byen for kundens forsendelsesadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_city")]
		public string ShipTo_City
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_city");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_City");
				this.SetAttributeValue("shipto_city", value);
				this.OnPropertyChanged("ShipTo_City");
			}
		}
		
		/// <summary>
		/// Viser den fulde leveringsadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_composite")]
		public string ShipTo_Composite
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_composite");
			}
		}
		
		/// <summary>
		/// Angiv navnet på den primære kontakt på kundens forsendelsesadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_contactname")]
		public string ShipTo_ContactName
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_contactname");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_ContactName");
				this.SetAttributeValue("shipto_contactname", value);
				this.OnPropertyChanged("ShipTo_ContactName");
			}
		}
		
		/// <summary>
		/// Angiv landet eller området for kundens forsendelsesadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_country")]
		public string ShipTo_Country
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_country");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_Country");
				this.SetAttributeValue("shipto_country", value);
				this.OnPropertyChanged("ShipTo_Country");
			}
		}
		
		/// <summary>
		/// Angiv faxnummeret for kundens forsendelsesadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_fax")]
		public string ShipTo_Fax
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_fax");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_Fax");
				this.SetAttributeValue("shipto_fax", value);
				this.OnPropertyChanged("ShipTo_Fax");
			}
		}
		
		/// <summary>
		/// Vælg fragtbetingelserne for at sikre, at forsendelsesordrer behandles korrekt.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_freighttermscode")]
		public virtual quote_shipto_freighttermscode? ShipTo_FreightTermsCode
		{
			get
			{
				return ((quote_shipto_freighttermscode?)(EntityOptionSetEnum.GetEnum(this, "shipto_freighttermscode")));
			}
			set
			{
				this.OnPropertyChanging("ShipTo_FreightTermsCode");
				this.SetAttributeValue("shipto_freighttermscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("ShipTo_FreightTermsCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_freighttermscodename")]
		public string ShipTo_FreightTermsCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("shipto_freighttermscode"))
				{
					return this.FormattedValues["shipto_freighttermscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Angiv den første linje i kundens forsendelsesadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line1")]
		public string ShipTo_Line1
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line1");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_Line1");
				this.SetAttributeValue("shipto_line1", value);
				this.OnPropertyChanged("ShipTo_Line1");
			}
		}
		
		/// <summary>
		/// Angiv den anden linje i kundens forsendelsesadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line2")]
		public string ShipTo_Line2
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line2");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_Line2");
				this.SetAttributeValue("shipto_line2", value);
				this.OnPropertyChanged("ShipTo_Line2");
			}
		}
		
		/// <summary>
		/// Angiv den tredje linje i forsendelsesadressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line3")]
		public string ShipTo_Line3
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line3");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_Line3");
				this.SetAttributeValue("shipto_line3", value);
				this.OnPropertyChanged("ShipTo_Line3");
			}
		}
		
		/// <summary>
		/// Angiv et navn til kundens forsendelsesadresse, f.eks. "Hovedsæde" eller "Afdelingskontor", for at identificere adressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_name")]
		public string ShipTo_Name
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_name");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_Name");
				this.SetAttributeValue("shipto_name", value);
				this.OnPropertyChanged("ShipTo_Name");
			}
		}
		
		/// <summary>
		/// Angiv postnummeret i forsendelsesadressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_postalcode")]
		public string ShipTo_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_postalcode");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_PostalCode");
				this.SetAttributeValue("shipto_postalcode", value);
				this.OnPropertyChanged("ShipTo_PostalCode");
			}
		}
		
		/// <summary>
		/// Angiv staten eller området for forsendelsesadressen.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_stateorprovince")]
		public string ShipTo_StateOrProvince
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_stateorprovince");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_StateOrProvince");
				this.SetAttributeValue("shipto_stateorprovince", value);
				this.OnPropertyChanged("ShipTo_StateOrProvince");
			}
		}
		
		/// <summary>
		/// Angiv telefonnummeret for kundens forsendelsesadresse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_telephone")]
		public string ShipTo_Telephone
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_telephone");
			}
			set
			{
				this.OnPropertyChanging("ShipTo_Telephone");
				this.SetAttributeValue("shipto_telephone", value);
				this.OnPropertyChanged("ShipTo_Telephone");
			}
		}
		
		/// <summary>
		/// Spring over prisberegning (til intern brug)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("skippricecalculation")]
		public virtual qooi_skippricecalculation? SkipPriceCalculation
		{
			get
			{
				return ((qooi_skippricecalculation?)(EntityOptionSetEnum.GetEnum(this, "skippricecalculation")));
			}
			set
			{
				this.OnPropertyChanging("SkipPriceCalculation");
				this.SetAttributeValue("skippricecalculation", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("SkipPriceCalculation");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("skippricecalculationname")]
		public string skippricecalculationName
		{
			get
			{
				if (this.FormattedValues.Contains("skippricecalculation"))
				{
					return this.FormattedValues["skippricecalculation"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Vælg den serviceaftale (SLA), du vil anvende på tilbudsposten.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
		public Microsoft.Xrm.Sdk.EntityReference SLAId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slaid");
			}
			set
			{
				this.OnPropertyChanging("SLAId");
				this.SetAttributeValue("slaid", value);
				this.OnPropertyChanged("SLAId");
			}
		}
		
		/// <summary>
		/// Sidste SLA, der blev anvendt til dette tilbud. Dette felt er kun beregnet til intern brug.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedid")]
		public Microsoft.Xrm.Sdk.EntityReference SLAInvokedId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slainvokedid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedidname")]
		public string SLAInvokedIdName
		{
			get
			{
				if (this.FormattedValues.Contains("slainvokedid"))
				{
					return this.FormattedValues["slainvokedid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaname")]
		public string SLAName
		{
			get
			{
				if (this.FormattedValues.Contains("slaid"))
				{
					return this.FormattedValues["slaid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.OnPropertyChanging("StageId");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("StageId");
			}
		}
		
		/// <summary>
		/// Viser, om tilbuddet er i kladdeform, aktivt, vundet eller lukket. Kun kladdetilbud kan redigeres.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual quote_statecode? StateCode
		{
			get
			{
				return ((quote_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StateCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Vælg tilbuddets status.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual quote_statuscode? StatusCode
		{
			get
			{
				return ((quote_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Viser det samlede forfaldne beløb, beregnet som summen af produkterne, rabatter, fragt og moms for tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount")]
		public Microsoft.Xrm.Sdk.Money TotalAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount");
			}
			set
			{
				this.OnPropertyChanging("TotalAmount");
				this.SetAttributeValue("totalamount", value);
				this.OnPropertyChanged("TotalAmount");
			}
		}
		
		/// <summary>
		/// Value of the Samlet beløb in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount_base");
			}
		}
		
		/// <summary>
		/// Viser det samlede forfaldne produktbeløb for tilbuddet, minus evt. rabatter. Denne værdi føjes til fragt- og momsbeløb i beregningen af det samlede forfaldne beløb for tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight")]
		public Microsoft.Xrm.Sdk.Money TotalAmountLessFreight
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight");
			}
			set
			{
				this.OnPropertyChanging("TotalAmountLessFreight");
				this.SetAttributeValue("totalamountlessfreight", value);
				this.OnPropertyChanged("TotalAmountLessFreight");
			}
		}
		
		/// <summary>
		/// Value of the Samlet beløb før fragt in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight_base")]
		public Microsoft.Xrm.Sdk.Money TotalAmountLessFreight_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight_base");
			}
		}
		
		/// <summary>
		/// Viser det samlede rabatbeløb, baseret på den rabatpris og -procent, der er angivet i tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount")]
		public Microsoft.Xrm.Sdk.Money TotalDiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount");
			}
			set
			{
				this.OnPropertyChanging("TotalDiscountAmount");
				this.SetAttributeValue("totaldiscountamount", value);
				this.OnPropertyChanged("TotalDiscountAmount");
			}
		}
		
		/// <summary>
		/// Value of the Samlet rabatbeløb in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalDiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount_base");
			}
		}
		
		/// <summary>
		/// Viser summen af alle eksisterende produkter og produkter, der skal rekvireres, som er inkluderet i tilbuddet, baseret på den angivne prisliste og de angivne mængder.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount");
			}
			set
			{
				this.OnPropertyChanging("TotalLineItemAmount");
				this.SetAttributeValue("totallineitemamount", value);
				this.OnPropertyChanged("TotalLineItemAmount");
			}
		}
		
		/// <summary>
		/// Value of the Samlet detailbeløb in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount_base");
			}
		}
		
		/// <summary>
		/// Viser de samlede manuelle rabatbeløb, der er angivet på alle de produkter, der er inkluderet i tilbuddet. Denne værdi vises i feltet Detaljebeløb i tilbuddet og føjes til alle de rabatbeløb eller -procenter, der er angivet i tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount");
			}
			set
			{
				this.OnPropertyChanging("TotalLineItemDiscountAmount");
				this.SetAttributeValue("totallineitemdiscountamount", value);
				this.OnPropertyChanged("TotalLineItemDiscountAmount");
			}
		}
		
		/// <summary>
		/// Value of the Samlet rabatbeløb for linjeelement in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount_base");
			}
		}
		
		/// <summary>
		/// Viser de samlede momsbeløb, der er angivet på alle de produkter, der er inkluderet i tilbuddet, som er inkluderet i beregningen af det samlede forfaldne beløb for tilbuddet.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax")]
		public Microsoft.Xrm.Sdk.Money TotalTax
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax");
			}
			set
			{
				this.OnPropertyChanging("TotalTax");
				this.SetAttributeValue("totaltax", value);
				this.OnPropertyChanged("TotalTax");
			}
		}
		
		/// <summary>
		/// Value of the Samlet moms in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax_base")]
		public Microsoft.Xrm.Sdk.Money TotalTax_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax_base");
			}
		}
		
		/// <summary>
		/// Vælg den lokale valuta til posten for at sikre, at budgetter rapporteres i den korrekte valuta.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyidname")]
		public string TransactionCurrencyIdName
		{
			get
			{
				if (this.FormattedValues.Contains("transactioncurrencyid"))
				{
					return this.FormattedValues["transactioncurrencyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.OnPropertyChanging("TraversedPath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("TraversedPath");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Vælg, om de produkter, der er inkluderet i tilbuddet, skal sendes til den angivne adresse eller sættes i venteposition, indtil kunden ringer med flere afhentnings- eller leveringsinstruktioner.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("willcall")]
		public System.Nullable<bool> WillCall
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("willcall");
			}
			set
			{
				this.OnPropertyChanging("WillCall");
				this.SetAttributeValue("willcall", value);
				this.OnPropertyChanged("WillCall");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("willcallname")]
		public string WillCallName
		{
			get
			{
				if (this.FormattedValues.Contains("willcall"))
				{
					return this.FormattedValues["willcall"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// N:N contactquotes_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contactquotes_association")]
		public System.Collections.Generic.IEnumerable<Boruto.Plugin.Entities.Contact> contactquotes_association
		{
			get
			{
				return this.GetRelatedEntities<Boruto.Plugin.Entities.Contact>("contactquotes_association", null);
			}
			set
			{
				this.OnPropertyChanging("contactquotes_association");
				this.SetRelatedEntities<Boruto.Plugin.Entities.Contact>("contactquotes_association", null, value);
				this.OnPropertyChanged("contactquotes_association");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_quotes
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_quotes")]
		public Boruto.Plugin.Entities.BusinessUnit business_unit_quotes
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.BusinessUnit>("business_unit_quotes", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_quote_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_quote_createdonbehalfby")]
		public Boruto.Plugin.Entities.SystemUser lk_quote_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.SystemUser>("lk_quote_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_quote_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_quote_modifiedonbehalfby")]
		public Boruto.Plugin.Entities.SystemUser lk_quote_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.SystemUser>("lk_quote_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_quotebase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_quotebase_createdby")]
		public Boruto.Plugin.Entities.SystemUser lk_quotebase_createdby
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.SystemUser>("lk_quotebase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_quotebase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_quotebase_modifiedby")]
		public Boruto.Plugin.Entities.SystemUser lk_quotebase_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.SystemUser>("lk_quotebase_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 msdyn_account_quote_Account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_account")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_account_quote_Account")]
		public Boruto.Plugin.Entities.Account msdyn_account_quote_Account
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.Account>("msdyn_account_quote_Account", null);
			}
			set
			{
				this.OnPropertyChanging("msdyn_account_quote_Account");
				this.SetRelatedEntity<Boruto.Plugin.Entities.Account>("msdyn_account_quote_Account", null, value);
				this.OnPropertyChanged("msdyn_account_quote_Account");
			}
		}
		
		/// <summary>
		/// N:1 opportunity_quotes
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opportunityid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opportunity_quotes")]
		public Boruto.Plugin.Entities.Opportunity opportunity_quotes
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.Opportunity>("opportunity_quotes", null);
			}
			set
			{
				this.OnPropertyChanging("opportunity_quotes");
				this.SetRelatedEntity<Boruto.Plugin.Entities.Opportunity>("opportunity_quotes", null, value);
				this.OnPropertyChanged("opportunity_quotes");
			}
		}
		
		/// <summary>
		/// N:1 quote_customer_accounts
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("quote_customer_accounts")]
		public Boruto.Plugin.Entities.Account quote_customer_accounts
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.Account>("quote_customer_accounts", null);
			}
			set
			{
				this.OnPropertyChanging("quote_customer_accounts");
				this.SetRelatedEntity<Boruto.Plugin.Entities.Account>("quote_customer_accounts", null, value);
				this.OnPropertyChanged("quote_customer_accounts");
			}
		}
		
		/// <summary>
		/// N:1 quote_customer_contacts
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("quote_customer_contacts")]
		public Boruto.Plugin.Entities.Contact quote_customer_contacts
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.Contact>("quote_customer_contacts", null);
			}
			set
			{
				this.OnPropertyChanging("quote_customer_contacts");
				this.SetRelatedEntity<Boruto.Plugin.Entities.Contact>("quote_customer_contacts", null, value);
				this.OnPropertyChanged("quote_customer_contacts");
			}
		}
		
		/// <summary>
		/// N:1 system_user_quotes
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("system_user_quotes")]
		public Boruto.Plugin.Entities.SystemUser system_user_quotes
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.SystemUser>("system_user_quotes", null);
			}
		}
		
		/// <summary>
		/// N:1 team_quotes
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_quotes")]
		public Boruto.Plugin.Entities.Team team_quotes
		{
			get
			{
				return this.GetRelatedEntity<Boruto.Plugin.Entities.Team>("team_quotes", null);
			}
		}
	}
}
#pragma warning restore CS1591
