#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boruto.Plugin.Entities
{
	
	
	/// <summary>
	/// Liste med forsyningstyper
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum vf_forsyning
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Gas = 979700006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Naturgas = 979700000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Andet = 979700001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Elvarme = 979700002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fjernblokvarme = 979700003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Olie = 979700004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Varmepumpe = 979700005,
	}
}
#pragma warning restore CS1591
