using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Metadata;
using System;
using System.Collections.Generic;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading.Tasks;


namespace Boruto.Tools
{
    public class Tool
    {
        public static bool IsPlugin { get; private set; } = false;

        internal static void SetIsPlguin()
        {
            IsPlugin = true;
        }

        private readonly IOrganizationService orgService;
        private const string BUILDER_FILENAME = "builderSettings.json";

        public Tool(Microsoft.Xrm.Sdk.IOrganizationService orgService)
        {
            this.orgService = orgService;
        }

        public void GenerateIUnitOfWork()
        {

            if (!System.IO.File.Exists(BUILDER_FILENAME))
            {
                Console.WriteLine($"No file  [{BUILDER_FILENAME}] was found in this directory");
                return;
            }

            using (var fac = new ServiceFactory(this.orgService, null, typeof(Tool).Assembly))
            {
                var meta = fac.Create<ServiceAPI.IMetadataService>();

                using (var fil = new System.IO.FileStream(BUILDER_FILENAME, System.IO.FileMode.Open))
                {
                    var ser = new System.Runtime.Serialization.Json.DataContractJsonSerializer(typeof(BuilderSettings));
                    var builderSettings = (BuilderSettings)ser.ReadObject(fil);

                    var map = new Dictionary<string, string>();

                    using (var file = new System.IO.StreamWriter($@"Uow\IUnitOfWork.design.cs"))
                    {
                        file.WriteLine("/*");
                        file.WriteLine($" * This file is autogenerated on { System.DateTime.Now.ToString("yyyy-MM-dd HH:mm") }. Manual changes will be overridden on next generate.");
                        file.WriteLine(" */");
                        file.WriteLine($"namespace {builderSettings.Namespace}");
                        file.WriteLine("{");

                        file.WriteLine($"\tpublic partial interface IUnitOfWork");
                        file.WriteLine("\t{");
                        var dubs = builderSettings.Dubs();
                        foreach (var entity in builderSettings.EntityNamesFilter)
                        {
                            var ent = meta.ForEntity(entity);
                            map[entity] = ent.SchemaName;
                            file.WriteLine($"\t\tIRepository<{ent.SchemaName}> {ent.SchemaName.ServiceNameOf(builderSettings.OmitEntityPrefix, dubs)} {{ get; }}");
                        }
                        file.WriteLine("\t}");

                        file.WriteLine("}");
                    }

                    using (var file = new System.IO.StreamWriter($@"Uow\CrmUnitOfWork.design.cs"))
                    {
                        file.WriteLine("/*");
                        file.WriteLine($" * This file is autogenerated on {System.DateTime.Now.ToString("yyyy-MM-dd HH:mm")}. Manual changes will be overridden on next generate.");
                        file.WriteLine(" */");

                        file.WriteLine($"namespace {builderSettings.Namespace}");
                        file.WriteLine("{");

                        file.WriteLine($"\tpublic partial class CrmUnitOfWork");
                        file.WriteLine("\t{");

                        var dubs = builderSettings.Dubs();
                        foreach (var entity in builderSettings.EntityNamesFilter)
                        {
                            var sn = map[entity];
                            file.WriteLine($"\t\tpublic IRepository<{sn}> {sn.ServiceNameOf(builderSettings.OmitEntityPrefix, dubs)} => GetRepository<{sn}>();");
                        }
                        file.WriteLine("\t}");

                        file.WriteLine("}");
                    }
                }
            }
        }

        public void GenerateOptionSetValueProperties()
        {

            if (!System.IO.File.Exists(BUILDER_FILENAME))
            {
                Console.WriteLine($"No file  [{BUILDER_FILENAME}] was found in this directory");
                return;
            }

            using (var fac = new ServiceFactory(this.orgService, null, typeof(Tool).Assembly))
            {
                var meta = fac.Create<ServiceAPI.IMetadataService>();

                using (var fil = new System.IO.FileStream(BUILDER_FILENAME, System.IO.FileMode.Open))
                {
                    var ser = new System.Runtime.Serialization.Json.DataContractJsonSerializer(typeof(BuilderSettings));
                    var builderSettings = (BuilderSettings)ser.ReadObject(fil);

                    var map = new Dictionary<string, string>();

                    using (var file = new System.IO.StreamWriter($@"Uow\OptionSetProperties.design.cs"))
                    {
                        file.WriteLine("/*");
                        file.WriteLine($" * This file is autogenerated on {System.DateTime.Now.ToString("yyyy-MM-dd HH:mm")}. Manual changes will be overridden on next generate.");
                        file.WriteLine(" */");
                        file.WriteLine("using Microsoft.Xrm.Sdk;");
                        file.WriteLine($"namespace {builderSettings.Namespace}");
                        file.WriteLine("{");

                        foreach (var entity in builderSettings.EntityNamesFilter)
                        {
                            var ent = meta.ForEntity(entity);

                            file.WriteLine($"\tpublic partial class { ent.SchemaName }");
                            file.WriteLine("\t{");
                            foreach (var attr in ent.Attributes)
                            {
                                string type = null;
                                if (attr.GetType() == typeof(Microsoft.Xrm.Sdk.Metadata.PicklistAttributeMetadata))
                                {
                                    type = "OptionSetValue";
                                }

                                if (attr.GetType() == typeof(Microsoft.Xrm.Sdk.Metadata.StatusAttributeMetadata))
                                {
                                    type = "OptionSetValue";
                                }

                                if (attr.GetType() == typeof(Microsoft.Xrm.Sdk.Metadata.MultiSelectPicklistAttributeMetadata))
                                {
                                    type = "OptionSetValueCollection";
                                }

                                if (type == null)
                                {
                                    continue;
                                }

                                if (attr is MultiSelectPicklistAttributeMetadata me)
                                {
                                    type = "OptionSetValueCollection";
                                }
                                file.WriteLine($"\t\t[AttributeLogicalName(Fields.{ attr.SchemaName })]");
                                file.WriteLine($"\t\tpublic {type} _{ attr.SchemaName }");
                                file.WriteLine("\t\t{");
                                file.WriteLine("\t\t\tget");
                                file.WriteLine("\t\t\t{");
                                file.WriteLine($"\t\t\t\tif (this.Attributes.ContainsKey(Fields.{attr.SchemaName})) return ({type})this[Fields.{attr.SchemaName}];");
                                file.WriteLine($"\t\t\t\treturn null;");
                                file.WriteLine("\t\t\t}");

                                file.WriteLine("\t\t\tset");
                                file.WriteLine("\t\t\t{");
                                file.WriteLine($"\t\t\t\tthis.OnPropertyChanging(Fields.{ attr.SchemaName });\r\n");
                                file.WriteLine($"\t\t\t\tthis[Fields.{attr.SchemaName}] = value;");
                                file.WriteLine($"\t\t\t\tthis.OnPropertyChanged(Fields.{attr.SchemaName});\r\n");
                                file.WriteLine("\t\t\t}");
                                file.WriteLine("\t\t}");
                                file.WriteLine("");
                                file.WriteLine("");
                            }

                            file.WriteLine("\t}");
                            file.WriteLine("");
                        }
                        file.WriteLine("}");
                    }
                }
            }
        }


        public static void FixActionMessageResponseSetters(string proxyMessagesPath)
        {
            if (!Directory.Exists(proxyMessagesPath))
            {
                Console.WriteLine($"ProxyMessages folder not found: {proxyMessagesPath}");
                return;
            }

            var files = Directory.GetFiles(proxyMessagesPath, "*.cs", SearchOption.AllDirectories);

            foreach (var file in files)
            {
                var lines = File.ReadAllLines(file);

                var insideResponseClass = false;
                var braceDepth = 0;
                var updated = false;

                for (int i = 0; i < lines.Length; i++)
                {
                    var line = lines[i];

                    // detect class start
                    if (line.Contains("class") &&
                        line.Contains("OrganizationResponse"))
                    {
                        insideResponseClass = true;
                        braceDepth = 0;
                        continue;
                    }

                    if (insideResponseClass)
                    {
                        if (line.Contains("{")) braceDepth++;
                        if (line.Contains("}")) braceDepth--;

                        if (line.Contains("this.Parameters["))
                        {
                            lines[i] = line.Replace("this.Parameters[", "this.Results[");
                            updated = true;
                        }

                        if (braceDepth <= 0)
                        {
                            insideResponseClass = false;
                        }
                    }
                }

                if (updated)
                {
                    File.WriteAllLines(file, lines, Encoding.UTF8);
                    Console.WriteLine($"Fixed: {Path.GetFileName(file)}");
                }
            }
        }

        [DataContract]
        internal class BuilderSettings
        {
            [DataMember(Name = "namespace")]
            public string Namespace { get; set; }

            [DataMember(Name = "entityNamesFilter")]
            public string[] EntityNamesFilter { get; set; }

            [DataMember(Name = "omitEntityPrefix")]
            public string[] OmitEntityPrefix { get; set; }

            internal string[] Dubs()
            {
                var all = (from s in EntityNamesFilter
                           select s.ServiceNameOf(this.OmitEntityPrefix, null)).ToArray();

                return (from a in all
                        group a by a into grp
                        select new
                        {
                            grp.Key,
                            grp.ToArray().Length
                        }).Where(r => r.Length > 1).Select(r => r.Key).ToArray();
            }
        }
    }

    internal static class ToolsLocalExtensions
    {
        internal static string ServiceNameOf(this string name, string[] ommitPrefix, string[] dubs)
        {
            var finalName = name;
            if (ommitPrefix != null && ommitPrefix.Length > 0)
            {
                foreach (var pre in ommitPrefix)
                {
                    if (finalName.StartsWith(pre))
                    {
                        finalName = finalName.Substring(pre.Length);
                    }
                }
            }

            var result = finalName.Substring(0, 1).ToUpper() + finalName.Substring(1) + "s";

            if (dubs != null && dubs.Contains(result))
            {
                return name.Substring(0, 1).ToUpper() + name.Substring(1) + "s";
            }

            return result;
        }
    }
}
