#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Boruto.Plugin.Entities
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class ServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public ServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Boruto.Plugin.Entities.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Boruto.Plugin.Entities.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<Boruto.Plugin.Entities.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Boruto.Plugin.Entities.bor_plugindemo"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Boruto.Plugin.Entities.bor_plugindemo> bor_plugindemoSet
		{
			get
			{
				return this.CreateQuery<Boruto.Plugin.Entities.bor_plugindemo>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Boruto.Plugin.Entities.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Boruto.Plugin.Entities.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<Boruto.Plugin.Entities.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Boruto.Plugin.Entities.Lead"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Boruto.Plugin.Entities.Lead> LeadSet
		{
			get
			{
				return this.CreateQuery<Boruto.Plugin.Entities.Lead>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Boruto.Plugin.Entities.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Boruto.Plugin.Entities.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<Boruto.Plugin.Entities.SystemUser>();
			}
		}
	}
}
#pragma warning restore CS1591
